[package]
name = "redis-driver"
version = "0.1.4"
keywords = ["redis", "database"]
categories = ["database", "asynchronous"]
description = "Redis async driver for Rust"
homepage = "https://github.com/dahomey-technologies/redis-driver-rs"
repository = "https://github.com/dahomey-technologies/redis-driver-rs"
documentation = "https://docs.rs/redis-driver"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"

[features]
default = ["tokio-runtime"]
tokio-runtime = [
    "tokio/macros",
    "tokio/net",
    "tokio/rt",
    "tokio/io-util",
]
async-std-runtime = [
    "async-std",
    "async-std/attributes",
    "tokio-util/compat",
]

[dependencies]
async-std = { version = "1", features = ["attributes"], optional = true }
futures = "0"
bytes = "1"
tokio = { version = "1" }
tokio-util = { version = "0", features = ["codec"] }
itoa = "1"

[dev-dependencies]
serial_test = "0"
tokio = { version = "1", features = ["time"] }
rand = "0.8.4"
